name: attendanddiscriminate
dataset_name: wear
devices: ['cuda:0']
anno_json: [
  'data/wear/annotations/wear_split_1.json',
  'data/wear/annotations/wear_split_2.json',
  'data/wear/annotations/wear_split_3.json'
]
dataset: {
  sens_folder: ./data/wear/raw/inertial,
  input_dim: 12,
  sampling_rate: 50,
  num_classes: 18,
  window_size: 25,
  window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  hidden_dim: 128,
  conv_kernels: 64,
  conv_kernel_size: 5,
  enc_layers: 2,
  enc_is_bidirectional: False,
  dropout: 0.5,
  dropout_rnn: 0.5,
  dropout_cls: 0.5,
  activation: 'ReLU', 
  sa_div: 1
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 300,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  batch_size: 100,
}